// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8xIfhUu-_VHUWq7YhvwAMHpgTSPkk1lk',
    appId: '1:548020309706:web:15e24982a6ae2bf9236e33',
    messagingSenderId: '548020309706',
    projectId: 'acitiviypoint',
    authDomain: 'acitiviypoint.firebaseapp.com',
    storageBucket: 'acitiviypoint.firebasestorage.app',
    measurementId: 'G-TGHTRTJMPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFiq7u-0Gx3uZNlwJRwxJW3K9EqKcIpI0',
    appId: '1:548020309706:android:8b194576efb7dc8d236e33',
    messagingSenderId: '548020309706',
    projectId: 'acitiviypoint',
    storageBucket: 'acitiviypoint.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1rI4Jago8Zki4sah1Qds7eQmtOE7-Oyc',
    appId: '1:548020309706:ios:81037f141586488e236e33',
    messagingSenderId: '548020309706',
    projectId: 'acitiviypoint',
    storageBucket: 'acitiviypoint.firebasestorage.app',
    iosBundleId: 'com.example.actitivyPointCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1rI4Jago8Zki4sah1Qds7eQmtOE7-Oyc',
    appId: '1:548020309706:ios:81037f141586488e236e33',
    messagingSenderId: '548020309706',
    projectId: 'acitiviypoint',
    storageBucket: 'acitiviypoint.firebasestorage.app',
    iosBundleId: 'com.example.actitivyPointCalculator',
  );
}
